### ISSUE TITLE
Process failing when game times are TBD

### ISSUE THREAD

**Issue by timhealz** [atthletics/bookie#1]
```
Traceback (most recent call last):
  File "scoreboard.py", line 124, in <module>
    Scoreboard(args.year, args.week).main(args.selector)
  File "scoreboard.py", line 107, in main
    self.parse_game_data()
  File "scoreboard.py", line 55, in parse_game_data
    date_raw = game.find('th', {'class': 'date-time'})['data-date']
  File "/home/healyt22/anaconda3/lib/python3.6/site-packages/bs4/element.py", line 1016, in __getitem__
    return self.attrs[key]
KeyError: 'data-date'
```

**Comment by timhealz** [comment]
Fixed. Defaulted to 1900-01-01 00:00:00
